version: 2

jobs:
  build:
    docker:
      - image: circleci/php:7.2-zts-node-browsers-legacy
        environment:
            MYSQL_HOST: 127.0.0.1
            MYSQL_DB: study
            MYSQL_USER: root
            MYSQL_PASSWORD: 123456
      - image: circleci/mysql:8.0.4
        environment:
            MYSQL_ROOT_PASSWORD: 123456
            MYSQL_USER: user
            MYSQL_ROOT_HOST: "%"
            MYSQL_DATABASE: study
            MYSQL_PASSWORD: 123456


    working_directory: ~/Laravel-Progressive

    steps:
      - checkout
      - run: sudo apt-get update
      - run: sudo apt install -y libsqlite3-dev zlib1g-dev
      - run:
          name: waiting for mysql to ready
          command: |
            for i in `seq 1 10`;
            do
              nc -z 127.0.0.1 3306 && echo Success && exit 0
              echo -n .
              sleep 1
            done
            echo Failed waiting for MySQL && exit 1
      - run:
          name: Install MySQL CLI; Import dummy data; run an example query
          command: |
            sudo apt-get install default-mysql-client
            mysql -h 127.0.0.1 -u user -p123456
            show databases;
            exit;
      - run: sudo docker-php-ext-install zip
      - run: sudo docker-php-ext-install pdo_mysql
      - run: sudo composer self-update
      - restore_cache:
          keys:
              - composer-v1-{{ checksum "composer.lock" }}
              - composer-v1-
      - run: mv env.test .env
      - run: composer install -n --ignore-platform-reqs
      - save_cache:
          key: composer-v1-{{ checksum "composer.lock" }}
          paths:
              - vendor
      - restore_cache: # special step to restore the dependency cache if `package.json` does not change
          keys:
              - node-v1-{{ checksum "package.json" }}
              # fallback to using the latest cache if no exact match is found (See https://circleci.com/docs/2.0/caching/)
              - node-v1-
      - run: npm install
      - save_cache: # special step to save the dependency cache with the `package.json` cache key template
          key: node-v1-{{ checksum "package.json" }}
          paths:
              - node_modules
      - run: npm run production
      - run:
          name: Mysql database
          command: mysql -h 127.0.0.1 -uroot -p123456 -e "create database study;"
      - run: php artisan key:generate
      - run: php artisan migrate
      - run: php artisan passport:install
      - run:
          name: Run Laravel Server
          command: php artisan serve
          background: true
      - run: vendor/bin/phpunit
      - run:
          name: Start Chrome Driver
          command: ./vendor/laravel/dusk/bin/chromedriver-linux
          background: true
      - run: mv env.dusk .env.dusk.local
      - run:
          name: Run Laravel Dusk Tests
          command: php artisan dusk
